Test curl, header preview

diff --git a/speedflow b/speedflow
--- a/speedflow
+++ b/speedflow
@@ -10,9 +10,15 @@ dep_check()
 #This is a simple test to check this script dependencies.
 
 if ! [ -x "$(command -v $1)" ]; then
-  echo "Error: $1 is not installed. Try apt-get install speedtest." >&2
+  echo "Error: $1 is not installed. Try apt-get install $1." >&2
   exit 1
 fi
+
+if ! [ -x "$(command -v $2)" ]; then
+  echo "Error: $2 is not installed. Try apt-get install $2." >&2
+  exit 1
+fi
+
 }
 
 run_speedtest()
@@ -44,6 +50,6 @@ logger()
 }
 
 load_config
-dep_check speedtest
+dep_check speedtest curl
 run_speedtest
 logger
